### ISSUE TITLE
& symbol in anchor tags

### ISSUE THREAD

**Issue by mrherndon** [JonathanWolfe/language-polymer#1]
If there is an & symbol in an anchor URL, it interprets the rest of the file as part of the attribute value.
with an ampersand:
![image](https://cloud.githubusercontent.com/assets/8726819/19390686/c63ba5c2-91ee-11e6-923b-c5061f555959.png)

without one:
![image](https://cloud.githubusercontent.com/assets/8726819/19390719/ef3e41a0-91ee-11e6-99b9-69ca34e0627f.png)

Obviously, ampersands are "normal" in URLs.

**Comment by JonathanWolfe** [comment]
Odd, I'll look into it. 

Are you on atom or vs code btw?

**Comment by mrherndon** [comment]
Vs code

**Comment by JonathanWolfe** [comment]
Fixed in [v0.7.7](/JonathanWolfe/language-polymer/releases/tag/v0.7.7).

Thanks for reporting!

**Comment by mrherndon** [comment]
Awesome man, thanks.

**Comment by mrherndon** [comment]
Just had a chance to fully check this out.  Works beautifully.  Thanks again.
