### ISSUE TITLE
Unable to format polymer files

### ISSUE THREAD

**Issue by jonadeline** [JonathanWolfe/language-polymer#6]
Hi,

After I associated HTML files to Polymer syntax I'm unable to format HTML files (alt+shift+f). It says no formatter is associated to Polymer files. Is there a workaround for this issue ?

Thanks.

**Comment by JonathanWolfe** [comment]
@Bodhiz: Not that I know of 😔. VSCode doesn't expose a way of mapping additional syntaxes to the default formatters.

Most of the various linters and formatter plugins do though, if you want to use something like Prettier, js-beautify, and the like.

**Comment by jonadeline** [comment]
Thanks for you answer @JonathanWolfe. 
I do use Prettier actually.

**Comment by JonathanWolfe** [comment]
Prettier's closest match for polymer is vue so you'll need to do a [config override](https://prettier.io/docs/en/configuration.html#configuration-overrides) like:

```json
{
  "overrides": [
    {
      "files": "*.html",
      "options": {
        "parser": "vue"
      }
    }
  ]
}
```
