### ISSUE TITLE
Toggle line comment has no effect 

### ISSUE THREAD

**Issue by danmindru** [JonathanWolfe/language-polymer#8]
Hi Jonathan,

I've noticed `Ctrl` + `/` has no effect when the language is set to Polymer (in any block: style, html, js).
It does work when I switch the language to Vue.

Any ideas on how to fix it?
Thanks :)

**Comment by JonathanWolfe** [comment]
I noticed that too recently but didn't know it worked for Vue. I'll have a look and see what they did.

**Comment by danmindru** [comment]
Wow, that was fast! Thanks Jon, awesome work 👍
